### ISSUE TITLE
Suggestion for no proxy server

### ISSUE THREAD

**Issue by junrau** [toddaustin07/edgeWeather#1]
I have a suggestion for allowing no proxy server.

I have a Node Red instance running, and have a flow that will take a URL as a parameter and return its response.

E.g.,  my weather URL is "https://api.weather.gov/stations/KAPA/observations/latest", and my Node Red instance is running at http://192.168.2.7:1880.  I can use a URL of "http://192.168.2.7:1880/proxy/get?url=https://api.weather.gov/stations/KAPA/observations/latest", and it will forward the request and return the response.

As such, I don't need a proper web proxy, or the Edge Bridge server, so it would have handy to have an option to not have to enter a proxy address.

Thanks.

**Comment by toddaustin07** [comment]
Hi - Is this something that anyone else would be able to take advantage of or is this unique to your setup?

If other Node Red users can do this, I can add a third option to the Proxy type preference setting.

**Comment by junrau** [comment]
I doubt this is common, but others pay have some other way to not need a proxy server, so it might be good to just have a no proxy option.

**Comment by toddaustin07** [comment]
A none option is now been added to the Proxy Type setting.
