### ISSUE TITLE
Tempest Weather Station addition

### ISSUE THREAD

**Issue by MABeatty1978** [toddaustin07/edgeWeather#2]
Hello,

I'd like to ask for the Tempest Weatherflow devices be added.  The API is [documented here](https://weatherflow.github.io/Tempest/api/swagger/#/) 

I will email you separately with my access tokens.  Thank you and let me know if I can help test anything.

**Comment by toddaustin07** [comment]
It’s coming!  I had already been working on it and if testing goes ok I may have it pushed out by tomorrow.

**Comment by toddaustin07** [comment]
WeatherFlow Tempest now supported, so closing this issue.
