### ISSUE TITLE
Bug in WU forecast, min/max temp

### ISSUE THREAD

**Issue by MABeatty1978** [toddaustin07/edgeWeather#3]
There is a bug in your code here:  the data.daypart attributes cover 12-hour day segment array, day/night.  You are parsing it looking for "Tomorrow".  The day part segment would go "Today" Tonight" Tomorrow", which should always hit on index[2].  However, the temperatureMin and temperatureMax values are not in the daypart array.  They are their own properties that are based off a 24 hour dayOfWeek array segment, when you are using the daypart array, value of 2 and applying it to the dayOfWeek array, you are actually getting the maxHigh and maxLow temps of the day AFTER tomorrow.    I THINK the dayOfWeek property is always going to be today, tomorrow, day after, etc.  So I think it would be safe to get the min/max with a hardcoded 1 .  This part of the API does not seem to be documented, so just a guess.

You can see in my json, daypartName "Tomorrow" is index 2, but index 2 of temperatureMax is actually Thrusday (today is Tuesday).  My app is showing a max temp for tomorrow being 63, when it should be 41

My current json:
```
"dayOfWeek":["Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
"temperatureMax":[null,41,63,28,39,45],"temperatureMin":[29,36,25,23,31,28]

"daypart":[{"daypartName":[null,"Tonight","Tomorrow","Tomorrow night","Thursday","Thursday night","Friday","Friday night","Saturday","Saturday night","Sunday","Sunday night"]"temperature":[50,28,52,30,53,30,55,33,53,33,51,31]
```

```
local function update_forecast(device, weatherdata)

  local weathertable = {}
  weathertable.forecast = {}

  local data, pos, err = json.decode (weatherdata, 1, nil)

  -- determine which forecast period is tomorrow
  
  if data.daypart[1] then
    local fc = data.daypart[1]
    local index
    for i=1, #fc.daypartName do
      log.debug ('Scanning:', fc.daypartName[i])
      if fc.daypartName[i] == 'Tomorrow' then; index = i; end
    end
    
    if index then
    
      log.debug (string.format('Using forecast index #%s', index))
      
      weathertable.forecast.temperature = {value=set0ifna(fc.temperature, index, 'temp')}
      weathertable.forecast.mintemp = {value=set0ifna(data.temperatureMin, index, 'temp')}
      weathertable.forecast.maxtemp = {value=set0ifna(data.temperatureMax, index, 'temp')}
      weathertable.forecast.humidity = {value=set0ifna(fc.relativeHumidity, index)}
      weathertable.forecast.precipprob = {value=set0ifna(fc.precipChance, index)}
      weathertable.forecast.cloudcover = {value=set0ifna(fc.cloudCover, index)}
      weathertable.forecast.windspeed = {value=set0ifna(fc.windSpeed, index)}
      
      weathertable.forecast.summary = {value=' '}
      if fc.wxPhraseLong then
        if fc.wxPhraseLong[index] then
          weathertable.forecast.summary = {value=fc.wxPhraseLong[index]}
        end
      end
      
      -- Unavailable
      weathertable.forecast.preciprate = {value=0}
      weathertable.forecast.windgust = {value=0}
        
        
      return weathertable
        
    else
      log.error ('Tomorow forecast not found')
    end
  else
    log.error ('Forecast data not found')
  end
end

```

**Comment by MABeatty1978** [comment]
I opened a pull request with suggested fix.

**Comment by toddaustin07** [comment]
Hi - thanks for bringing this up.

 _the temperatureMin and temperatureMax values are not in the daypart array. They are their own properties that are based off a 24 hour dayOfWeek array segment_

Is this documented somewhere?  I hadn't understood that to be the case, thus why I coded it the way I did.  Glad to stand corrected, just curious to know if/where that is explained in the docs.

Hardcoding an index is ugly, but may be right that a hardcoded index of 1 could be the solution, however, let's make sure this is the case for all times of day - especially, say 11:45pm!

I happened to be doing some updates on this driver now, so can incorporate this fix and get it out fairly quickly.

**Comment by MABeatty1978** [comment]
I wouldn't have caught it if it wasn't for the fact that we are having such a big temperature swing.  Our normal temps for this time a year hover between 20 and 30.  There is a significant warm front coming in on Thursday pushing the temps up above 60.  I saw, the ST app was showing Wednesday's temp high at 61, I confirmed that weather.com was also showing 61 being the high on Thursday, so I knew something wasn't right so I dove into your code and the weather.com api.  I've never touched the weather.com api, but I have worked quite a bit with the NWS api, so I had a pretty good idea what I was looking for.

To avoid the hardcoded 2, I think you can do a similar function 
```
if data.dayOfWeek[1] then
    local fc = data.dayOfWeek[1]
    local index
    for i=1, #fc.dayOfWeek do
      log.debug ('Scanning:', fc.dayOfWeek[i])
      if fc.dayOfWeek[i] == os.date(%A) then; index = i+1; end
    end
```
This would find the index that is the current day of the week from the os, then get the index for the following day.

**Comment by toddaustin07** [comment]
Do you know what the difference is between the temperatureMin/Max fields and the calendarDayTemperatureMin/Max fields?  I've noticed that the values can be different.

Regarding the logic to extract the min/max temp values from the right array position:  I would assume the dayOfWeek array is based on **local** time, not UTC time.  In Edge, we can't get the local time - only UTC time, so os.date() returns UTC time.  This means I can't compare os.date(%A) to the dayOfWeek field directly, but will have to adjust for the local time offset.  Fortunately there is a field in the forecast data (validTimeLocal) from which I can parse the offset.

**Comment by MABeatty1978** [comment]
> Do you know what the difference is between the temperatureMin/Max fields and the calendarDayTemperatureMin/Max fields? I've noticed that the values can be different.

No, calendarDayTemperatureMin/Max isn't covered anywhere in [the documentation](https://developer.ibm.com/apis/catalog/weather--weather-forecast-apis/api/API--weather--daily-forecast-api-3_0#SUNv3DailyForecast).  temperatureMax/Min are, however, so I would trust them over the calendarDay values.

**Comment by toddaustin07** [comment]
Updated driver as been pushed out: version **2023-02-23T03:40:27.249589545**

Please confirm this corrects the min/max temperature forecast values for you.

**Comment by MABeatty1978** [comment]
> Updated driver as been pushed out: version **2023-02-23T03:40:27.249589545**
> 
> Please confirm this corrects the min/max temperature forecast values for you.

Pardon my ignorance (Edge is still pretty new to me), but how do I update the driver on my hub?  I've read I can reboot my hub or wait 12 hours, I've rebooted my hub and the driver is still showing up as 2022-11-22.  It has only been 7 hours, so do I just need to wait?

**Comment by toddaustin07** [comment]
The driver gets automated automatically, and I'm surprised it's taking this long.  I know that SmartThings has said up to 12 hours originally, but it is usually much faster than that.

Be sure your hub is enrolled in my test channel here:  https://bestow-regional.api.smartthings.com/invite/Q1jP7BqnNNlL
You should have selected the **Edge Weather V1** driver to install.

To force an immediate update you need the CLI tool and you'd issue this command:
smartthings edge:drivers:install

You'd be prompted for the channel (from the list of channels your hub is enrolled in) and the driver to install.

**Comment by MABeatty1978** [comment]
I was able to get it updated with the CLI.  However, I'm still seeing tomorrows forcasted Hi/Low as being for Saturday.

**Comment by toddaustin07** [comment]
You'll have to provide me some data, as it seems to be working OK as far as I can tell.

Please post the data as received (plug the forecast URL into a browser), as well as a screen shot of the app.  And also confirm the local time you did the data refresh and confirm your timezone.

**Comment by MABeatty1978** [comment]
It is correct this morning, I'll keep an eye on it and report back if I see anything.
