### ISSUE TITLE
Not working with OpenWeather one-call api 3.0

### ISSUE THREAD

**Issue by iferlive** [toddaustin07/edgeWeather#5]
I just found that the edgeweather driver dos not work with PAYG plans in OpenWeather, In order to use all the EdgeWeather features I decided to use the OpenWeather one-call API, this API pulls weather and forecast in a single call, it provides all the extra values than the ones provided by the free 2.5 API like illuminance and UV index, my edgebridge receives the GET request and forwards the call output to the edge driver but it does not update the values in the driver, looks like the output is not compatible with the driver.

Example: 
https://api.openweathermap.org/data/3.0/onecall?lat=20.7167&lon=-103.4&appid=xxxxxxxxxxxxxx

Output:

// 20230227163413
// https://api.openweathermap.org/data/3.0/onecall?lat=20.7167&lon=-103.4&appid=xxxxxxxxxxxxxx

{
  "lat": 20.7167,
  "lon": -103.4,
  "timezone": "America/Mexico_City",
  "timezone_offset": -21600,
  "current": {
    "dt": 1677537252,
    "sunrise": 1677503739,
    "sunset": 1677545843,
    "temp": 303.12,
    "feels_like": 301.27,
    "pressure": 1008,
    "humidity": 15,
    "dew_point": 273.7,
    "uvi": 1.68,
    "clouds": 18,
    "visibility": 10000,
    "wind_speed": 3.13,
    "wind_deg": 223,
    "wind_gust": 6.71,
    "weather": [
      {
        "id": 801,
        "main": "Clouds",
        "description": "few clouds",
        "icon": "02d"
      }
    ]
  },
  "hourly": [
    {
      "dt": 1677535200,
      "temp": 303.2,
      "feels_like": 301.32,
      "pressure": 1008,
      "humidity": 14,
      "dew_point": 272.85,
      "uvi": 4.38,
      "clouds": 19,
      "visibility": 10000,
      "wind_speed": 2.66,
      "wind_deg": 285,
      "wind_gust": 3.66,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677538800,
      "temp": 303.12,
      "feels_like": 301.27,
      "pressure": 1008,
      "humidity": 15,
      "dew_point": 273.7,
      "uvi": 1.68,
      "clouds": 18,
      "visibility": 10000,
      "wind_speed": 2.44,
      "wind_deg": 304,
      "wind_gust": 3.73,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677542400,
      "temp": 302.8,
      "feels_like": 301.01,
      "pressure": 1008,
      "humidity": 14,
      "dew_point": 272.57,
      "uvi": 0.32,
      "clouds": 17,
      "visibility": 10000,
      "wind_speed": 2.72,
      "wind_deg": 324,
      "wind_gust": 3.56,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677546000,
      "temp": 300.14,
      "feels_like": 299.15,
      "pressure": 1009,
      "humidity": 17,
      "dew_point": 273.05,
      "uvi": 0,
      "clouds": 13,
      "visibility": 10000,
      "wind_speed": 1.99,
      "wind_deg": 325,
      "wind_gust": 2.55,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677549600,
      "temp": 297.11,
      "feels_like": 296.11,
      "pressure": 1010,
      "humidity": 21,
      "dew_point": 273.47,
      "uvi": 0,
      "clouds": 9,
      "visibility": 10000,
      "wind_speed": 1.5,
      "wind_deg": 273,
      "wind_gust": 1.86,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677553200,
      "temp": 293.9,
      "feels_like": 292.74,
      "pressure": 1012,
      "humidity": 27,
      "dew_point": 274.24,
      "uvi": 0,
      "clouds": 8,
      "visibility": 10000,
      "wind_speed": 1.97,
      "wind_deg": 237,
      "wind_gust": 2.17,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677556800,
      "temp": 290.32,
      "feels_like": 289.01,
      "pressure": 1014,
      "humidity": 35,
      "dew_point": 274.5,
      "uvi": 0,
      "clouds": 27,
      "visibility": 10000,
      "wind_speed": 1.95,
      "wind_deg": 236,
      "wind_gust": 2.24,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677560400,
      "temp": 289.3,
      "feels_like": 288.02,
      "pressure": 1015,
      "humidity": 40,
      "dew_point": 275.64,
      "uvi": 0,
      "clouds": 39,
      "visibility": 10000,
      "wind_speed": 1.7,
      "wind_deg": 252,
      "wind_gust": 1.75,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677564000,
      "temp": 288.09,
      "feels_like": 286.87,
      "pressure": 1015,
      "humidity": 47,
      "dew_point": 276.82,
      "uvi": 0,
      "clouds": 37,
      "visibility": 10000,
      "wind_speed": 1.55,
      "wind_deg": 249,
      "wind_gust": 1.57,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677567600,
      "temp": 287.26,
      "feels_like": 286.11,
      "pressure": 1016,
      "humidity": 53,
      "dew_point": 277.61,
      "uvi": 0,
      "clouds": 6,
      "visibility": 10000,
      "wind_speed": 1.41,
      "wind_deg": 270,
      "wind_gust": 1.46,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677571200,
      "temp": 286.52,
      "feels_like": 285.43,
      "pressure": 1016,
      "humidity": 58,
      "dew_point": 278.2,
      "uvi": 0,
      "clouds": 17,
      "visibility": 10000,
      "wind_speed": 1.39,
      "wind_deg": 273,
      "wind_gust": 1.47,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677574800,
      "temp": 285.83,
      "feels_like": 284.77,
      "pressure": 1016,
      "humidity": 62,
      "dew_point": 278.59,
      "uvi": 0,
      "clouds": 19,
      "visibility": 10000,
      "wind_speed": 0.97,
      "wind_deg": 304,
      "wind_gust": 1.12,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677578400,
      "temp": 285.58,
      "feels_like": 284.52,
      "pressure": 1015,
      "humidity": 63,
      "dew_point": 278.68,
      "uvi": 0,
      "clouds": 31,
      "visibility": 10000,
      "wind_speed": 0.25,
      "wind_deg": 331,
      "wind_gust": 0.55,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677582000,
      "temp": 285.14,
      "feels_like": 284.09,
      "pressure": 1015,
      "humidity": 65,
      "dew_point": 278.61,
      "uvi": 0,
      "clouds": 27,
      "visibility": 10000,
      "wind_speed": 0.26,
      "wind_deg": 167,
      "wind_gust": 0.47,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677585600,
      "temp": 284.95,
      "feels_like": 283.88,
      "pressure": 1016,
      "humidity": 65,
      "dew_point": 278.56,
      "uvi": 0,
      "clouds": 34,
      "visibility": 10000,
      "wind_speed": 0.62,
      "wind_deg": 142,
      "wind_gust": 0.68,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677589200,
      "temp": 284.65,
      "feels_like": 283.58,
      "pressure": 1017,
      "humidity": 66,
      "dew_point": 278.38,
      "uvi": 0,
      "clouds": 65,
      "visibility": 10000,
      "wind_speed": 0.79,
      "wind_deg": 138,
      "wind_gust": 0.84,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677592800,
      "temp": 286.71,
      "feels_like": 285.61,
      "pressure": 1017,
      "humidity": 57,
      "dew_point": 278.33,
      "uvi": 0.48,
      "clouds": 35,
      "visibility": 10000,
      "wind_speed": 1.19,
      "wind_deg": 104,
      "wind_gust": 1.37,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677596400,
      "temp": 291.27,
      "feels_like": 290.23,
      "pressure": 1016,
      "humidity": 42,
      "dew_point": 278.17,
      "uvi": 2.07,
      "clouds": 47,
      "visibility": 10000,
      "wind_speed": 1.21,
      "wind_deg": 111,
      "wind_gust": 1.61,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677600000,
      "temp": 295.28,
      "feels_like": 294.38,
      "pressure": 1015,
      "humidity": 32,
      "dew_point": 277.61,
      "uvi": 4.79,
      "clouds": 60,
      "visibility": 10000,
      "wind_speed": 0.93,
      "wind_deg": 103,
      "wind_gust": 1.29,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677603600,
      "temp": 299.84,
      "feels_like": 299.11,
      "pressure": 1014,
      "humidity": 22,
      "dew_point": 276.66,
      "uvi": 8.03,
      "clouds": 48,
      "visibility": 10000,
      "wind_speed": 0.75,
      "wind_deg": 84,
      "wind_gust": 1.02,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677607200,
      "temp": 303.11,
      "feels_like": 301.29,
      "pressure": 1013,
      "humidity": 17,
      "dew_point": 275.69,
      "uvi": 10.56,
      "clouds": 47,
      "visibility": 10000,
      "wind_speed": 0.39,
      "wind_deg": 89,
      "wind_gust": 1.05,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677610800,
      "temp": 305.23,
      "feels_like": 302.99,
      "pressure": 1011,
      "humidity": 14,
      "dew_point": 274.71,
      "uvi": 11.74,
      "clouds": 0,
      "visibility": 10000,
      "wind_speed": 0.04,
      "wind_deg": 280,
      "wind_gust": 2.19,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677614400,
      "temp": 305.82,
      "feels_like": 303.49,
      "pressure": 1009,
      "humidity": 13,
      "dew_point": 273.99,
      "uvi": 10.49,
      "clouds": 28,
      "visibility": 10000,
      "wind_speed": 0.49,
      "wind_deg": 257,
      "wind_gust": 3.15,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677618000,
      "temp": 305.47,
      "feels_like": 303.19,
      "pressure": 1008,
      "humidity": 13,
      "dew_point": 273.8,
      "uvi": 7.64,
      "clouds": 52,
      "visibility": 10000,
      "wind_speed": 0.87,
      "wind_deg": 254,
      "wind_gust": 3.1,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677621600,
      "temp": 303.31,
      "feels_like": 301.42,
      "pressure": 1007,
      "humidity": 15,
      "dew_point": 273.51,
      "uvi": 3.34,
      "clouds": 64,
      "visibility": 10000,
      "wind_speed": 1.59,
      "wind_deg": 260,
      "wind_gust": 3.13,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677625200,
      "temp": 303.53,
      "feels_like": 301.58,
      "pressure": 1006,
      "humidity": 14,
      "dew_point": 273.52,
      "uvi": 1.28,
      "clouds": 70,
      "visibility": 10000,
      "wind_speed": 2.26,
      "wind_deg": 266,
      "wind_gust": 3.64,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677628800,
      "temp": 302.7,
      "feels_like": 300.94,
      "pressure": 1007,
      "humidity": 15,
      "dew_point": 273.61,
      "uvi": 0.24,
      "clouds": 60,
      "visibility": 10000,
      "wind_speed": 2.23,
      "wind_deg": 265,
      "wind_gust": 3.11,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677632400,
      "temp": 297.11,
      "feels_like": 296.11,
      "pressure": 1008,
      "humidity": 21,
      "dew_point": 273.65,
      "uvi": 0,
      "clouds": 70,
      "visibility": 10000,
      "wind_speed": 1.37,
      "wind_deg": 258,
      "wind_gust": 1.49,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677636000,
      "temp": 295.06,
      "feels_like": 293.96,
      "pressure": 1010,
      "humidity": 25,
      "dew_point": 273.82,
      "uvi": 0,
      "clouds": 85,
      "visibility": 10000,
      "wind_speed": 2.12,
      "wind_deg": 228,
      "wind_gust": 3.85,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677639600,
      "temp": 293.57,
      "feels_like": 292.4,
      "pressure": 1012,
      "humidity": 28,
      "dew_point": 274.37,
      "uvi": 0,
      "clouds": 90,
      "visibility": 10000,
      "wind_speed": 2.56,
      "wind_deg": 234,
      "wind_gust": 5.24,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677643200,
      "temp": 292.01,
      "feels_like": 290.79,
      "pressure": 1014,
      "humidity": 32,
      "dew_point": 274.91,
      "uvi": 0,
      "clouds": 92,
      "visibility": 10000,
      "wind_speed": 2.22,
      "wind_deg": 244,
      "wind_gust": 3.63,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677646800,
      "temp": 290.39,
      "feels_like": 289.19,
      "pressure": 1014,
      "humidity": 39,
      "dew_point": 276.01,
      "uvi": 0,
      "clouds": 93,
      "visibility": 10000,
      "wind_speed": 2.18,
      "wind_deg": 238,
      "wind_gust": 2.7,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677650400,
      "temp": 289.08,
      "feels_like": 287.88,
      "pressure": 1015,
      "humidity": 44,
      "dew_point": 276.81,
      "uvi": 0,
      "clouds": 92,
      "visibility": 10000,
      "wind_speed": 1.76,
      "wind_deg": 233,
      "wind_gust": 1.83,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677654000,
      "temp": 288.4,
      "feels_like": 287.23,
      "pressure": 1015,
      "humidity": 48,
      "dew_point": 277.25,
      "uvi": 0,
      "clouds": 100,
      "visibility": 10000,
      "wind_speed": 1.43,
      "wind_deg": 244,
      "wind_gust": 1.39,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677657600,
      "temp": 287.71,
      "feels_like": 286.58,
      "pressure": 1015,
      "humidity": 52,
      "dew_point": 277.67,
      "uvi": 0,
      "clouds": 100,
      "visibility": 10000,
      "wind_speed": 1.16,
      "wind_deg": 250,
      "wind_gust": 1.25,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677661200,
      "temp": 287.17,
      "feels_like": 286.09,
      "pressure": 1015,
      "humidity": 56,
      "dew_point": 278.24,
      "uvi": 0,
      "clouds": 100,
      "visibility": 10000,
      "wind_speed": 1.14,
      "wind_deg": 249,
      "wind_gust": 1.13,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677664800,
      "temp": 286.57,
      "feels_like": 285.53,
      "pressure": 1015,
      "humidity": 60,
      "dew_point": 278.8,
      "uvi": 0,
      "clouds": 100,
      "visibility": 10000,
      "wind_speed": 0.87,
      "wind_deg": 252,
      "wind_gust": 1.01,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677668400,
      "temp": 286,
      "feels_like": 285.04,
      "pressure": 1016,
      "humidity": 65,
      "dew_point": 279.33,
      "uvi": 0,
      "clouds": 100,
      "visibility": 10000,
      "wind_speed": 0.77,
      "wind_deg": 232,
      "wind_gust": 0.81,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677672000,
      "temp": 285.6,
      "feels_like": 284.7,
      "pressure": 1016,
      "humidity": 69,
      "dew_point": 279.76,
      "uvi": 0,
      "clouds": 100,
      "visibility": 10000,
      "wind_speed": 0.67,
      "wind_deg": 214,
      "wind_gust": 0.81,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677675600,
      "temp": 285.37,
      "feels_like": 284.55,
      "pressure": 1017,
      "humidity": 73,
      "dew_point": 280.41,
      "uvi": 0,
      "clouds": 91,
      "visibility": 10000,
      "wind_speed": 1.21,
      "wind_deg": 177,
      "wind_gust": 1.21,
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677679200,
      "temp": 287.16,
      "feels_like": 286.44,
      "pressure": 1017,
      "humidity": 70,
      "dew_point": 281.54,
      "uvi": 0.33,
      "clouds": 70,
      "visibility": 10000,
      "wind_speed": 1.09,
      "wind_deg": 170,
      "wind_gust": 1.51,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677682800,
      "temp": 291.44,
      "feels_like": 290.79,
      "pressure": 1017,
      "humidity": 56,
      "dew_point": 282.48,
      "uvi": 1.41,
      "clouds": 71,
      "visibility": 10000,
      "wind_speed": 0.73,
      "wind_deg": 226,
      "wind_gust": 1.59,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677686400,
      "temp": 295.22,
      "feels_like": 294.63,
      "pressure": 1016,
      "humidity": 44,
      "dew_point": 282.25,
      "uvi": 3.94,
      "clouds": 70,
      "visibility": 10000,
      "wind_speed": 1.14,
      "wind_deg": 257,
      "wind_gust": 2.13,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677690000,
      "temp": 298.46,
      "feels_like": 297.86,
      "pressure": 1015,
      "humidity": 31,
      "dew_point": 280.26,
      "uvi": 6.6,
      "clouds": 58,
      "visibility": 10000,
      "wind_speed": 1.83,
      "wind_deg": 271,
      "wind_gust": 3.27,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677693600,
      "temp": 300.34,
      "feels_like": 299.44,
      "pressure": 1014,
      "humidity": 23,
      "dew_point": 277.52,
      "uvi": 8.67,
      "clouds": 58,
      "visibility": 10000,
      "wind_speed": 2.67,
      "wind_deg": 274,
      "wind_gust": 4.71,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677697200,
      "temp": 301.62,
      "feels_like": 300.2,
      "pressure": 1012,
      "humidity": 19,
      "dew_point": 275.86,
      "uvi": 11.36,
      "clouds": 54,
      "visibility": 10000,
      "wind_speed": 3.68,
      "wind_deg": 274,
      "wind_gust": 5.52,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677700800,
      "temp": 302.42,
      "feels_like": 300.75,
      "pressure": 1011,
      "humidity": 17,
      "dew_point": 275.21,
      "uvi": 10.15,
      "clouds": 77,
      "visibility": 10000,
      "wind_speed": 4.13,
      "wind_deg": 269,
      "wind_gust": 5.95,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    },
    {
      "dt": 1677704400,
      "temp": 302.92,
      "feels_like": 301.12,
      "pressure": 1010,
      "humidity": 16,
      "dew_point": 274.27,
      "uvi": 7.4,
      "clouds": 84,
      "visibility": 10000,
      "wind_speed": 3.67,
      "wind_deg": 264,
      "wind_gust": 5.86,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "pop": 0
    }
  ],
  "daily": [
    {
      "dt": 1677524400,
      "sunrise": 1677503739,
      "sunset": 1677545843,
      "moonrise": 1677522660,
      "moonset": 1677482940,
      "moon_phase": 0.25,
      "temp": {
        "day": 302.57,
        "min": 284.42,
        "max": 303.28,
        "night": 289.3,
        "eve": 300.14,
        "morn": 284.42
      },
      "feels_like": {
        "day": 300.83,
        "night": 288.02,
        "eve": 299.15,
        "morn": 282.86
      },
      "pressure": 1011,
      "humidity": 13,
      "dew_point": 271.52,
      "wind_speed": 2.84,
      "wind_deg": 274,
      "wind_gust": 4.36,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "clouds": 74,
      "pop": 0,
      "uvi": 12.05
    },
    {
      "dt": 1677610800,
      "sunrise": 1677590094,
      "sunset": 1677632267,
      "moonrise": 1677611940,
      "moonset": 1677572640,
      "moon_phase": 0.29,
      "temp": {
        "day": 305.23,
        "min": 284.65,
        "max": 305.82,
        "night": 290.39,
        "eve": 297.11,
        "morn": 284.65
      },
      "feels_like": {
        "day": 302.99,
        "night": 289.19,
        "eve": 296.11,
        "morn": 283.58
      },
      "pressure": 1011,
      "humidity": 14,
      "dew_point": 274.71,
      "wind_speed": 2.56,
      "wind_deg": 234,
      "wind_gust": 5.24,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": 0,
      "pop": 0,
      "uvi": 11.74
    },
    {
      "dt": 1677697200,
      "sunrise": 1677676447,
      "sunset": 1677718690,
      "moonrise": 1677701400,
      "moonset": 1677662280,
      "moon_phase": 0.32,
      "temp": {
        "day": 301.62,
        "min": 285.37,
        "max": 303.12,
        "night": 288.58,
        "eve": 296.71,
        "morn": 285.37
      },
      "feels_like": {
        "day": 300.2,
        "night": 287.33,
        "eve": 295.7,
        "morn": 284.55
      },
      "pressure": 1012,
      "humidity": 19,
      "dew_point": 275.86,
      "wind_speed": 4.13,
      "wind_deg": 269,
      "wind_gust": 6.95,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "clouds": 54,
      "pop": 0,
      "uvi": 11.36
    },
    {
      "dt": 1677783600,
      "sunrise": 1677762800,
      "sunset": 1677805113,
      "moonrise": 1677790980,
      "moonset": 1677751680,
      "moon_phase": 0.35,
      "temp": {
        "day": 299.32,
        "min": 284.16,
        "max": 303.18,
        "night": 289.85,
        "eve": 299.68,
        "morn": 284.16
      },
      "feels_like": {
        "day": 299.32,
        "night": 288.31,
        "eve": 299.68,
        "morn": 283.25
      },
      "pressure": 1011,
      "humidity": 22,
      "dew_point": 275.76,
      "wind_speed": 5.11,
      "wind_deg": 291,
      "wind_gust": 7.87,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": 29,
      "pop": 0,
      "uvi": 12.16
    },
    {
      "dt": 1677870000,
      "sunrise": 1677849152,
      "sunset": 1677891535,
      "moonrise": 1677880620,
      "moonset": 1677840900,
      "moon_phase": 0.38,
      "temp": {
        "day": 300.37,
        "min": 283.61,
        "max": 303.32,
        "night": 290.35,
        "eve": 301.59,
        "morn": 283.61
      },
      "feels_like": {
        "day": 299.28,
        "night": 288.86,
        "eve": 300.09,
        "morn": 281.96
      },
      "pressure": 1007,
      "humidity": 16,
      "dew_point": 272.71,
      "wind_speed": 3.77,
      "wind_deg": 265,
      "wind_gust": 5.59,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": 1,
      "pop": 0,
      "uvi": 11.77
    },
    {
      "dt": 1677956400,
      "sunrise": 1677935504,
      "sunset": 1677977957,
      "moonrise": 1677970200,
      "moonset": 1677929820,
      "moon_phase": 0.41,
      "temp": {
        "day": 300.35,
        "min": 282.74,
        "max": 303.25,
        "night": 290.63,
        "eve": 301.23,
        "morn": 282.74
      },
      "feels_like": {
        "day": 299.36,
        "night": 288.77,
        "eve": 299.82,
        "morn": 282.74
      },
      "pressure": 1010,
      "humidity": 20,
      "dew_point": 275.21,
      "wind_speed": 2.65,
      "wind_deg": 306,
      "wind_gust": 3.37,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": 5,
      "pop": 0,
      "uvi": 12
    },
    {
      "dt": 1678042800,
      "sunrise": 1678021855,
      "sunset": 1678064379,
      "moonrise": 1678059720,
      "moonset": 1678018560,
      "moon_phase": 0.44,
      "temp": {
        "day": 301.42,
        "min": 283.65,
        "max": 305.37,
        "night": 293.22,
        "eve": 302.98,
        "morn": 283.65
      },
      "feels_like": {
        "day": 299.99,
        "night": 291.96,
        "eve": 301.16,
        "morn": 282.01
      },
      "pressure": 1014,
      "humidity": 15,
      "dew_point": 271.9,
      "wind_speed": 2.05,
      "wind_deg": 205,
      "wind_gust": 2.67,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": 4,
      "pop": 0,
      "uvi": 12
    },
    {
      "dt": 1678129200,
      "sunrise": 1678108205,
      "sunset": 1678150800,
      "moonrise": 1678149180,
      "moonset": 1678107060,
      "moon_phase": 0.48,
      "temp": {
        "day": 303.36,
        "min": 286.29,
        "max": 305.62,
        "night": 295.88,
        "eve": 302.89,
        "morn": 286.29
      },
      "feels_like": {
        "day": 301.77,
        "night": 295.07,
        "eve": 301.15,
        "morn": 285.36
      },
      "pressure": 1015,
      "humidity": 25,
      "dew_point": 281.45,
      "wind_speed": 3.29,
      "wind_deg": 247,
      "wind_gust": 8.11,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "clouds": 52,
      "pop": 0,
      "uvi": 12
    }
  ]
}

**Comment by toddaustin07** [comment]
Hi - Thanks for the request.  There was another community member who asked for this as well and said they were going to possibly go ahead and write up the code to support the V3 interface.  I've just sent him a message to see if he has done anything on it or still intends to.  If not, I'll look at adding this.

I may need you to privately share your appid with me so I can test.

**Comment by iferlive** [comment]
Thank you for your quick reply, I'll be glad to share an api key, let me know where I can send you one. 

Cheers!

**Comment by toddaustin07** [comment]
Hi - can you please send me your key info to rpi.smartthings@gmail.com ?

Thank you!

**Comment by iferlive** [comment]
Hello, sorry for the late reply. The driver has been working steady and all the fields are populating correctly with the 3.0 API. Thank you so much for integrating it into your driver. Feel free to keep the API Key and use it as long as you wish.

Thanks again mate.
